version: '3.11'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
  app:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    container_name: fastapi_app
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017